version: '3.8'

services:
  sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_skiShop
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Pass123
    ports:
      - "1433:1433"
    networks:
      - skinet-network
    volumes:
      - sqlserverdata:/var/opt/mssql

  redis:
    image: redis:7
    container_name: redis_skiShop
    ports:
      - "6379:6379"
    networks:
      - skinet-network
    volumes:
      - redisdata:/data

volumes:
  sqlserverdata:
  redisdata:

networks:
  skinet-network:
    driver: bridge
